### ISSUE TITLE
Exercise 5 completed!

### ISSUE THREAD

**Issue by SigmaMichaeldesanta** [CodeWithHarry/Sigma-Web-Dev-Course#117]
Solution :
HTML:-

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Layout</title>
    <link rel="stylesheet" href="style.css" />
  </head>
  <body>
    <nav class="Navbar">
      <ul>
        <li>Home</li>
        <li>Blogs</li>
        <li>Terms</li>
        <li>Conatact Us</li>
        <li>About</li>
      </ul>
    </nav>
    <div class="logo">
      <h1>Code With Harry</h1>
    </div>

    <div class="container">
      <div class="rightbox">
        <h1>About Harry</h1>
        <p>
          Meet Harry, the altruistic wizard of the digital realm, a passionate
          YouTuber on a mission to democratize coding education. With a
          contagious enthusiasm for programming, Harry dedicates his channel to
          unlocking the secrets of coding for aspiring developers worldwide—free
          of charge.
        </p>
      </div>
      <div class="leftbox">
        <h1>Services Provided</h1>
        <p>
          Harry, the YouTube coding maestro, offers a digital banquet of
          services in computer science. Delve into Python development with him,
          explore the realms of AI and ML, and master the art of Data Structures
          and Algorithms. Harry's channel is a one-stop-shop for aspiring
          coders.
        </p>
      </div>
    </div>
    <div class="welcome">
      <h1>Welcome To Sigma Web Dev Express</h1>
      <p>
        Welcome to Sigma Web Dev Express, where digital visions come to life!
        Our web development journey transcends boundaries, guided by innovation
        and fueled by expertise. Whether you seek dynamic websites, responsive
        designs, or seamless user experiences, our team is here to transform
        your ideas into captivating online realities.
      </p>
    </div>
    <div class="fixedarrow">
      <h1>^</h1>
    </div>
    <div class="footer">
      <div class="firsttext">
        <h2>Code With Harry</h2>
        <p>It is a channel</p>
      </div>
      <div class="secondtext">
        <h2>DummyWebsite</h2>
        <p>It is a dummy website</p>
      </div>
    </div>
  </body>
</html>

``` 
CSS:-
```css
@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap");
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: "Poppins", sans-serif;
}
body {
  background-color: whitesmoke;
}
nav ul {
  background-color: #310a31;
  padding: 40px;
  text-align: right;
}
nav ul li {
  color: #ff3085;
  list-style: none;
  display: inline;
  font-weight: 500;
  font-size: 20px;
  margin-left: 30px;
}
.Navbar {
  position: sticky;
  top: 0;
}
.logo{
    position: fixed;
    top: 25px;
    left: 25px;
    color: aliceblue;
}

.fixedarrow{
    position: fixed;
    top: 85%;
    left: 95%;
    background-color: cyan;
    color: #000000;
    border: 2px solid black;
    border-radius: 20px;
    /* top | right | bottom | left */
    padding: 5px 20px 5px 20px;
}
.container{
    background-color: #14e18b;
    height: 500px;
}
.rightbox {
  display: inline-block;
  background-color: #ffba39;
  height: 300px;
  width: 45%;
  padding: 10px;
  margin: 15px 25px;
  text-align: center;
  border-radius: 20px;
}
.leftbox {
  display: inline-block;
  background-color: rgb(68, 68, 255);
  height: 300px;
  width: 45%;
  padding: 10px;
  margin: 15px 25px;
  text-align: center;
  border-radius: 20px;
}
.welcome {
    text-align: center;
    border: 2px solid black;
    border-style: dashed;
    border-radius: 35px;
    padding: 15px;
    /* top | right | bottom | left */
    margin: 20px 30px 20px 30px;
}
.footer {
  background-color: black;
  color: white;
  height: 300px;
}
.firsttext{
    display: inline-block;
    margin: 15px 25px;
}
.secondtext{
    display: inline-block;
    margin: 15px 25px;
}

```
