### ISSUE TITLE
Exercise 8 completed

### ISSUE THREAD

**Issue by SigmaMichaeldesanta** [CodeWithHarry/Sigma-Web-Dev-Course#131]
HTML:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CSS Bounce Animation</title>
    <link rel="stylesheet" href="Animation.css" />
  </head>
  <body>
    <div class="container">
      <div class="ball"></div>
    </div>
  </body>
</html>

``` 

CSS:
```css
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
body {
  background-color: rgb(88, 88, 88);
}
.container {
  height: 100vh;
  display: flex;
  justify-content: flex-start;
  align-items: flex-end;
}
.ball {
  background-color: rgb(255, 104, 104);
  width: 10rem;
  height: 10rem;
  border-radius: 50%;
  /* animation: name duration timing-function delay iteration-count direction fill-mode; */
  animation: BouncingBalls 5s linear infinite alternate-reverse;
}
@keyframes BouncingBalls {
  0% {
    transform: translate(0, 0);
  }
  20% {
    transform: translate(10vw, -100px);
  }
  40% {
    transform: translate(20vw, -200px);
  }
  60% {
    transform: translate(30vw, -100px);
  }
  80% {
    transform: translate(40vw, -0px);
  }
  100% {
    transform: translate(50vw, -100px);
  }
  
}

```
